#!/usr/bin/env bash
# .env loading with the contract's precedence order (docs/reference/workshop-env-contract.md):
# OS environment WINS over .env, which wins over the defaults. This is what lets the replica
# process (Ansible) inject per-clone values into the OS without touching the file (F-REAL-ENV-2).
#
# Usage: the calling script sets ROOT (repo root) and does:
#   . "$ROOT/scripts/lib/env-load.sh"
#   load_env_os_first
#
# Requires bash (uses ${!var} and export -p).

# Snapshot of the exported environment → source .env → snapshot re-applied on top.
# `export -p` emits `declare -x VAR="…"`; inside a function that would create a LOCAL variable,
# so we swap it for `export` (same assignment syntax) before the eval.
load_env_os_first() {
  local _snap
  _snap="$(export -p | sed 's/^declare -x/export/')"
  set -a
  # shellcheck disable=SC1091
  [ -f "$ROOT/.env" ] && . "$ROOT/.env"
  set +a
  eval "$_snap"
  # INSTANCE (unique name created by the replica/Splunk Show) IS the instance label: when
  # present, it ALWAYS wins over DEPLOYMENT_ENVIRONMENT — including the .env one that the units
  # load via EnvironmentFile (indistinguishable from OS env inside the process). Without INSTANCE
  # (dev/laptop), nothing changes.
  if [ -n "${INSTANCE:-}" ]; then
    export DEPLOYMENT_ENVIRONMENT="$INSTANCE"
  fi
}

# Materializes the EFFECTIVE environment (merged OS>.env) into $ROOT/.env.runtime, consumed by
# compose.plain.yml via env_file — this is how the OS override reaches INSIDE the container.
# Only writes keys that exist in .env or .env.example (including ones commented out there,
# e.g. OWNER_PASSWORD) AND are set in the environment — preserves empty-vs-absent semantics.
write_env_runtime() {
  local out="$ROOT/.env.runtime"
  local keys key
  keys="$(
    { [ -f "$ROOT/.env" ] && grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$ROOT/.env"
      [ -f "$ROOT/.env.example" ] && grep -oE '^#? ?[A-Za-z_][A-Za-z0-9_]*=' "$ROOT/.env.example"
    } | tr -d '# ' | sed 's/=$//' | sort -u
  )"
  : > "$out"
  chmod 600 "$out"
  {
    echo "# Generated by scripts/up.sh on every start — DO NOT edit; DO NOT commit."
    echo "# Effective environment (OS > .env) delivered to the container via env_file (compose.plain.yml)."
    for key in $keys; do
      if [ -n "${!key+x}" ]; then
        printf '%s=%s\n' "$key" "${!key}"
      fi
    done
  } >> "$out"
}
